// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface Window {
  electron: {
    apiKeys: {
      set(service: "openai" | "anthropic", apiKey: string): Promise<void>;
      get(service: "openai" | "anthropic"): Promise<string | null>;
      remove(service: "openai" | "anthropic"): Promise<void>;
    };
    mcp: {
      send(message: MCPMessage): void;
      onReply(callback: (message: MCPMessageReply) => void): void;
      removeListener(callback: (message: MCPMessageReply) => void): void;
    };
    settings: {
      open(): void;
      removeListener(callback: () => void): void;
    };
  };
}
