// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface Window {
  electron: {
    ipcRenderer: {
      send(channel: string, data: any): void;
      on(channel: string, func: (...args: any[]) => void): void;
      removeListener(channel: string, func: (...args: any[]) => void): void;
    };
    apiKeys: {
      set(service: "openai" | "anthropic", apiKey: string): Promise<void>;
      get(service: "openai" | "anthropic"): Promise<string | null>;
      remove(service: "openai" | "anthropic"): Promise<void>;
    };
  };
}
